// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChuhcMYmbQY-qV6r_9bKVGvdqZ9k-Wo_s',
    appId: '1:692919346587:android:b01271a8ed906260956d3e',
    messagingSenderId: '692919346587',
    projectId: 'limit-spending',
    storageBucket: 'limit-spending.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY15ZVdKHEx01i4DC_wRPaPXl1JbFlyCw',
    appId: '1:692919346587:ios:fd79e075e75c7e65956d3e',
    messagingSenderId: '692919346587',
    projectId: 'limit-spending',
    storageBucket: 'limit-spending.firebasestorage.app',
    iosBundleId: 'com.tektonsoftware.limitspending',
  );

}